7 - CMS/MVC/Controllers/ModalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin_usuarios.Models;
using System.Web.Hosting;
using Newtonsoft.Json;
using System.IO;
using Microsoft.WindowsAzure.ServiceRuntime;
using System.Configuration;

namespace admin_usuarios.Controllers
{
    public class ModalController : Controller
    {
        // GET: Modal
        public ActionResult Index()
        {
            if (Session["User"] != null)
            {
                ModalCinema m = new ModalCinema();
                m.CinemaCode = int.Parse(ConfigurationManager.AppSettings["ModalCinemaCode"].ToString());
                string url = ConfigurationManager.AppSettings["Services.Proxy.Url"].ToString() + ConfigurationManager.AppSettings["Concession.ModalEstatus"].ToString();
                Service service = new Service();
                m = service.Execute<ModalCinema, ModalCinema>("Concession.ModalEstatus", m, url);
                if (m.CinemaCode != 0 && m.CinemaName != null)
                {
                    List<ModalCinema> cines = new List<ModalCinema>();
                    cines.Add(m);
                    return View(cines);
                }
                else
                {
                    return View(m.GetListCinema());
                }
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        public ActionResult Modifymodal(List<ModalCinema> model)
        {
            if (ModelState.IsValid)
            {
                Message response = new Message();
                string filePath = string.Empty;
                ModalCinema mCinema = model.Where(c => c.CinemaCode == int.Parse(ConfigurationManager.AppSettings["ModalCinemaCode"])).SingleOrDefault();
                mCinema.DateChanged = DateTime.Now;
                string ListaJson = JsonConvert.SerializeObject(mCinema);
                var cadena = System.Configuration.ConfigurationManager.AppSettings["Services.Proxy.Url"].ToString()
                    + System.Configuration.ConfigurationManager.AppSettings["Concession.ModifyModal"].ToString();
                Service ser = new Service();
                response = ser.Execute<string, Message>("Concession.ModifyModal", ListaJson, cadena);
                //#if DEBUG
                //                filePath = HostingEnvironment.MapPath("~/App_Data/ModalConcessions.txt");
                //#endif
                //#if (!DEBUG)
                //                string cachePath = RoleEnvironment.GetLocalResource("Messages").RootPath;
                //                filePath = Path.Combine(cachePath, "ModalConcessions.txt");
                //#endif



                //                if (!System.IO.File.Exists(filePath))
                //                {
                //                    System.IO.File.Create(filePath).Close();
                //                    using (StreamWriter Sw = new StreamWriter(filePath, false))
                //                    {
                //                        Sw.WriteLine(ListaJson);
                //                        Sw.Close();
                //                    };
                //                    Service ser = new Service();
                //                    //invocar el metodo de Wcf ppublish para hacer caching del archivo en formato json

                //                    //Concession.svc/ModifyModalConcessions/

                //                    response = ser.Execute<string, Message>("Concession.ModifyModal", ListaJson, cadena);
                //                }
                //                else
                //                {
                //                    using (StreamWriter Sw = new StreamWriter(filePath, false))
                //                    {
                //                        Sw.WriteLine(ListaJson);
                //                        Sw.Close();
                //                    };
                //                    Service ser = new Service();
                //                    //invocar el metodo de Wcf ppublish para hacer caching del archivo en formato json
                //                    // response = ser.Execute<string, Message>("Concession.ModifyModal", ListaJson);
                //                    response = ser.Execute<string, Message>("Concession.ModifyModal", ListaJson, cadena);
                //                }
                if (!response.error)
                {
                    ViewBag.text = "Se realizó la modificacion de forma exitosa!";
                    ViewBag.Error = "";
                }
                else
                {
                    ViewBag.text = "Hubo un problema con la actualización de los dartos!";
                    ViewBag.Error = response.message;
                }
            }
            return View();
        }

        public ActionResult VerifyModal()
        {
            try
            {
                if (Session["User"] != null)
                {
                    List<ModalCinema> modalCinemas = new List<ModalCinema>();
                    string url = ConfigurationManager.AppSettings["Services.Proxy.Url"].ToString() + ConfigurationManager.AppSettings["Concession.AllModalEstatus"].ToString();
                    Service service = new Service();
                    modalCinemas = service.Execute<List<ModalCinema>>("Concession.AllModalEstatus");
                    return View(modalCinemas);
                }
                else
                {
                    return RedirectToAction("Login", "Account");
                }
            }
            catch (Exception Ex)
            {
                var mensaje = Ex.Message;
                throw;
            }
        }
    }
}

7 - CMS/MVC/Views/Modal/Index.cshtml
@model List<admin_usuarios.Models.ModalCinema>
<div class="page-header">
    <h2>Asignacion de Carameleria por cine - Ventana Modal</h2>
</div>

<style>
    .botonredondo {
        position: fixed;
        border-radius: 15px;
        bottom: 35px;
        right: 35px;
        height: 35px;
        width: 35px;
        background-color: #c02328;
    }
</style>

<div class="row">
    @using (Html.BeginForm("Modifymodal", "Modal", FormMethod.Post, null))
    {
        if (Model != null)
        {
            foreach (var item in Model)
            {
                var index = Model.IndexOf(item);
                <div class="col-xs-6 col-md-4 col-lg-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            @item.CinemaName
                            @Html.HiddenFor(m => Model[index].CinemaName)
                            @Html.HiddenFor(m => Model[index].CinemaCode)
                            @Html.HiddenFor(m => Model[index].DateChanged)
                        </div>
                        <div class="panel-body">
                            @Html.HiddenFor(m => Model[index].ModalEnabled, new { @class = "enabled" })
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    @if (item.ModalEnabled)
                                    {
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary si">Si</button>
                                            <button type="button" class="btn btn-default no">No</button>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="btn-group text-center">
                                            <button type="button" class="btn btn-default si">Si</button>
                                            <button type="button" class="btn btn-danger no">No</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            @item.DateChanged.ToString()
                        </div>
                    </div>
                </div>
            }
            <div class="botonredondo">
                @*<input type="submit" />*@
                <button type="submit" name="Guardar" value="Guargar"><i class="fa fa-save fa-2x"></i></button>
            </div>
        }
        else
        {
            <div class="col-xs-12">
                <div class="jumbotron">
                    <h1>Ventana modal de Caramelería</h1>
                    <p>
                        Este cine no esta configurado para controlar el comportameinto de la ventana modal de caramelería.
                        por favor verifique esta configuración con el personal de soporte.
                    </p>
                </div>
            </div>
        }
    }
</div>

@section scripts{
    <script>
        $(".si").click(function () {
            $(this).addClass("btn-primary");
            $(this).removeClass("btn-default");
            $(this).closest("div").children(".no").removeClass("btn-danger");
            $(this).closest("div").children(".no").addClass("btn-default");
            $(this).closest(".panel-body").children(".enabled").val("True");
            //$(this).closest("div").closest("div").closest("div").closest("div").children("#item_ModalEnabled").val("False");
        });

        $(".no").click(function () {
            $(this).addClass("btn-danger");
            $(this).removeClass("btn-default");
            $(this).closest("div").children(".si").removeClass("btn-primary");
            $(this).closest("div").children(".si").addClass("btn-default");
            $(this).closest("div").children("#item_ModalEnabled").val("True");
            $(this).closest(".panel-body").children(".enabled").val("False");

        })
    </script>
}

7 - CMS/MVC/Views/Modal/Modifymodal.cshtml
<div class="page-header">
    <h2>Asignacion de Carameleria por cine - Ventana Modal</h2>
</div>

<div class="jumbotron">
    <h2>@ViewBag.text</h2>
    <p>@ViewBag.error</p>
</div>

7 - CMS/MVC/Views/Modal/VerifyModal.cshtml
@model List<admin_usuarios.Models.ModalCinema>
<div class="page-header">
    <h2>Ventanas Modales</h2>
</div>

<style>
    .botonredondo {
        position: fixed;
        border-radius: 15px;
        bottom: 35px;
        right: 35px;
        height: 35px;
        width: 35px;
        background-color: #c02328;
    }
</style>

<div class="row">
    @using (Html.BeginForm("Modifymodal", "Modal", FormMethod.Post, null))
    {
        if (Model != null)
        {
            foreach (var item in Model)
            {
                var index = Model.IndexOf(item);
                <div class="col-xs-6 col-md-4 col-lg-3">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            @item.CinemaName
                            @Html.HiddenFor(m => Model[index].CinemaName)
                            @Html.HiddenFor(m => Model[index].CinemaCode)
                            @Html.HiddenFor(m => Model[index].DateChanged)
                        </div>
                        <div class="panel-body">
                            @Html.HiddenFor(m => Model[index].ModalEnabled, new { @class = "enabled" })
                            <div class="row">
                                <div class="col-xs-12 text-center">
                                    @if (item.ModalEnabled)
                                    {
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary si">Si</button>
                                            <button type="button" class="btn btn-default no">No</button>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="btn-group text-center">
                                            <button type="button" class="btn btn-default si">Si</button>
                                            <button type="button" class="btn btn-danger no">No</button>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="panel-footer">
                            @item.DateChanged.ToString()
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="col-xs-12">
                <div class="jumbotron">
                    <h1>Ventana modal de Caramelería</h1>
                    <p>
                        Por favor intente nuevamente si el problema persiste contacte con el equipo de soporte.
                    </p>
                </div>
            </div>
        }
    }
</div>