7 - CMS/MVC/Models/TransferViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace admin_usuarios.Models
{
    public class TransferViewModel
    {
        public List<TransferItem> ItemsForSelect { get; set; }

        public List<TransferItem> ItemsSelected { get; set; }

        public TransferViewModel()
        {
            ItemsForSelect = new List<TransferItem>();
            ItemsSelected = new List<TransferItem>();
        }
    }
}

7 - CMS/MVC/Controllers/transfersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using admin_usuarios.Models;
using System.IO;
using System.Web.Hosting;
using Newtonsoft.Json;
using System.Configuration;

namespace admin_usuarios.Controllers
{
    public class transfersController : Controller
    {
        // GET: transfers
        public ActionResult Index()
        {
            TransferViewModel model = new TransferViewModel();
            Service service = new Service();
            model.ItemsForSelect = service.Execute<List<TransferItem>>("Concession.GetConcessionsItemsForCinema");
            model.ItemsForSelect.Add(new TransferItem
            {
                itemCode = "0",
                itemDescription = "Seleccione..",
            });
            return View(model);
        }

        [HttpPost]
        public ActionResult Transfer(TransferViewModel model, string item, string action, int quantity = 0)
        {
            if (action != "send" && (item == null || item == string.Empty || item == "0" || quantity <= 0))
            {
                ViewBag.mensaje = "Seleccione el item y la cantidad que desea trasladar";
                return View("Index", model);
            }
            switch (action)
            {
                case "add":
                    model.ItemsSelected = model.ItemsSelected.Where(m => m.Quitar == false).ToList();
                    var ItemToAdd = model.ItemsForSelect.Where(i => i.itemCode == item).SingleOrDefault();
                    var verify = model.ItemsSelected.Where(i => i.itemCode == item).SingleOrDefault();
                    if (verify != null)
                    {
                        int i = model.ItemsSelected.IndexOf(verify);
                        model.ItemsSelected[i].Quantity += quantity;
                    }
                    else
                    {
                        ItemToAdd.Quantity = quantity;
                        model.ItemsSelected.Add(ItemToAdd);
                    }
                    break;

                case "send":
                    model.ItemsSelected = model.ItemsSelected.Where(m => m.Quitar == false).ToList();
                    Service ser = new Service();
                    List<ItemAndComponets> items = ser.Execute<List<TransferItem>, List<ItemAndComponets>>("Concession.VerifyItemsForTranslate", model.ItemsSelected);
                    return View("TransferConfirmation", items);

                default:
                    break;
            }
            ModelState.Clear();
            return View("Index", model);
        }

        [HttpPost]
        public ActionResult TransferResume(List<ItemAndComponets> model)
        {
            //guardar la lista de items a tranferir en un archivo txt para luego de hacer el traslado en vista, actualizar la tabla de la nube
            string ruta = HostingEnvironment.MapPath("~/App_Data/traslado.txt");
            var itemsPrincipales = model.Select(m => m.PrincipalItem).ToList();
            using (StreamWriter wr = new StreamWriter(ruta, false))
            {
                wr.WriteLine(JsonConvert.SerializeObject(itemsPrincipales));
                wr.Close();
            }
            //validar cantidades totales de la transaccin
            List<ItemComponent> lista = new List<ItemComponent>();
            foreach (var item in model)
            {
                foreach (var item2 in item.ItemComponents)
                {
                    //se sustituye la cantidad original por la cantidad requerida para saber la cantidad real que se desea trasladar
                    if (item.PrincipalItem.itemType == null || item.PrincipalItem.itemType == string.Empty)
                    {
                        lista.Add(item2);
                    }
                    else
                    {
                        item2.ComponentOriginalQty = item2.ComponentOriginalQty * (decimal)item.PrincipalItem.Quantity;
                        lista.Add(item2);
                    }
                }
            }

            //agrupo los items de la lista resultasnte para evitar hacer varios movimimentos del mismo item
            //agrupo por el master id para segurarme de que no haya problemas en la insersion en vista.
            lista = lista.GroupBy(l => l.MasterID).Select(y => new ItemComponent
            {
                ComponentDescription = y.First().ComponentDescription,
                ComponentId = y.First().ComponentId,
                ComponentStock = y.First().ComponentStock,
                ComponentOriginalQty = y.Sum(q => q.ComponentOriginalQty),
                MasterID = y.First().MasterID,
                UOM = y.First().UOM
            }).ToList();
            ViewBag.option = "1";
            return View(lista);
        }

        public ActionResult VerifyCandies()
        {
            string cinemaId = ConfigurationManager.AppSettings["ModalCinemaCode"].ToString();
            Service ser = new Service();
            var url = System.Configuration.ConfigurationManager.AppSettings["Services.Proxy.Url"].ToString()
                   + System.Configuration.ConfigurationManager.AppSettings["Concession.GetConcessionsItemsInCinema"].ToString();
            var datos = ser.Execute<string, List<ItemAndComponets>>("Concession.GetConcessionsItemsInCinema", cinemaId, url);
            foreach (var item in datos)
            {
                foreach (var i in item.ItemComponents)
                {
                    if (item.PrincipalItem.itemType == "S")
                    {
                        i.ComponentOriginalQty *= item.PrincipalItem.Quantity;
                    }
                }
            }
            ModelState.Clear();
            datos.ToList();
            return View(datos);
        }

        public ActionResult TransferConfirm(List<ItemComponent> components)
        {
            Service ser = new Service();
            var resultado = ser.Execute<List<ItemComponent>, List<ItemComponent>>("Concession.ConfirmItemsForTranslate", components);
            int itemsTransferidos = resultado.Where(r => r.ComponentId.Contains("OK")).Count();
            if (itemsTransferidos != components.Count())
            {
                //resultado = resultado.Where(r => r.ComponentDescription.Contains("Ok")).ToList();
                resultado = ser.Execute<List<ItemComponent>, List<ItemComponent>>("Concession.ReverseTranslate", resultado);
                ViewBag.mensaje = "Hubo un problema al Trasladar los items en vista. el traslado de inventario fue reversado";
                ViewBag.option = "2";
                return View("TransferResume", components);
            }
            //una vez hechos los traslados en vista
            //invocar servicio para actualizar la tabla de la nube a traves de los servicios de la pagina web
            string ruta = HostingEnvironment.MapPath("~/App_Data/traslado.txt");
            List<TransferItem> items = new List<TransferItem>();
            using (StreamReader r = new StreamReader(ruta))
            {
                items = JsonConvert.DeserializeObject<List<TransferItem>>(r.ReadLine());
                r.Close();
            }
            var url = System.Configuration.ConfigurationManager.AppSettings["Services.Proxy.Url"].ToString()
                   + System.Configuration.ConfigurationManager.AppSettings["Concession.UpdateCandiesTable"].ToString();
            PackViewModel pvm = new PackViewModel
            {
                cinemaId = ConfigurationManager.AppSettings["ModalCinemaCode"].ToString(),
                items = items
            };
            TransferPack respuesta = ser.Execute<PackViewModel, TransferPack>("Concession.UpdateCandiesTable", pvm, url);

            //validar si se actualizó o no la tabal de azure; de ser negativa la actualizacion hago reverso del traslado en vista.
            //Concession.ReverseTranslate
            if (respuesta == null || respuesta.Token != "00")
            {
                resultado = ser.Execute<List<ItemComponent>, List<ItemComponent>>("Concession.ReverseTranslate", components);
                ViewBag.mensaje = "Hubo un problema al actualizar la tabla de azure. el traslado de inventario fue reversado";
            }

            //retornar la vista
            ViewBag.option = "2";
            foreach (var item in resultado)
            {
                item.ComponentStock -= item.ComponentOriginalQty;
            }
            return View("TransferResume", resultado);
        }

        /// <summary>
        /// obtener las concesiones disponibles en la web para luego decidir cuales se van a retornar al almacen de predespacho,
        /// </summary>GetAviableConcessionsItemsInCinema
        /// <returns></returns>
        public ActionResult WebToPre()
        {
            string cinemaId = ConfigurationManager.AppSettings["ModalCinemaCode"].ToString();
            Service ser = new Service();
            var url = System.Configuration.ConfigurationManager.AppSettings["Services.Proxy.Url"].ToString()
                   + System.Configuration.ConfigurationManager.AppSettings["Concession.GetAviableConcessionsItemsInCinema"].ToString();
            var datos = ser.Execute<string, List<TransferItem>>("Concession.GetAviableConcessionsItemsInCinema", cinemaId, url);
            List<ReverseViewModel> model = new List<ReverseViewModel>();
            foreach (var item in datos)
            {
                model.Add((ReverseViewModel)item);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult VerifyWebToPre(List<ReverseViewModel> model)
        {
            var m2 = model.Where(m => m.Quantity > 0).ToList();
            if (m2.Count > 0)
            {
                List<TransferItem> lista = new List<TransferItem>();
                foreach (var item in m2)
                {
                    lista.Add((TransferItem)item);
                }

7 - CMS/MVC/Views/transfers/Index.cshtml
@model admin_usuarios.Models.TransferViewModel

<div class="page-header">
    <h2>Transferencias de inventario - Items de Caramelería</h2>
</div>

@using (Html.BeginForm("Transfer", "transfers", FormMethod.Post))
{
    <div class="well well-sm">
       <div class="row">
           <div class="col-xs-4">
               <div class="form-group">
                   @foreach (var s in Model.ItemsForSelect)
                {
                    int i = Model.ItemsForSelect.IndexOf(s);
                       @Html.HiddenFor(m => Model.ItemsForSelect[i].itemCode)
                       @Html.HiddenFor(m => Model.ItemsForSelect[i].itemDescription)
                       @Html.HiddenFor(m => Model.ItemsForSelect[i].itemType)
                       @Html.HiddenFor(m => Model.ItemsForSelect[i].itemCode)
                       @Html.HiddenFor(m => Model.ItemsForSelect[i].Quitar)
                       @Html.HiddenFor(m => Model.ItemsForSelect[i].UnidadDeMedida)
                   }
                   <label>Item</label>
                   @Html.DropDownList("item", new SelectList(Model.ItemsForSelect, "itemCode", "itemDescription", "0"), new { @class = "form-control", @id = "item" })
               </div>
           </div>

           <div class="col-xs-2">
               <label>Cantidad</label>
               <input type="number" name="quantity" id="quantity" min="0" class="form-control" />
           </div>
           <div class="col-xs-2">
               <label>Agregar</label>
               <button type="submit" name="action" value="add" class="btn btn-default btn-block"><span class="fa fa-plus-circle"></span></button>
           </div>
           <div class="col-xs-2">
               <label>Enviar Transferencia</label>
               <button type="submit" name="action" value="send" class="btn btn-primary btn-block"><span class="fa fa-check"></span></button>
           </div>
       </div>
        @if (ViewBag.mensaje != null)
        {
            <label class="label label-danger">@ViewBag.mensaje</label>
        }
    </div>

    <h4>Items Seleccionados para esta Transferencia</h4>
    <hr />
    if (Model.ItemsSelected.Count > 0)
    {
        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Descripcion</th>
                    <th class="text-right">Cantidad</th>
                    <th class="text-right">Medida</th>
                    <th class="text-center">Remover</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ItemsSelected)
                {
                    int i = Model.ItemsSelected.IndexOf(item);
                    <tr class="@i">
                        
                        <td>@Model.ItemsSelected[i].itemCode</td>
                        <td>@Model.ItemsSelected[i].itemDescription</td>
                        <td class="text-right">@Model.ItemsSelected[i].Quantity.ToString("N0")</td>
                        <td class="text-right">@Model.ItemsSelected[i].UnidadDeMedida</td>
                        @Html.HiddenFor(m => Model.ItemsSelected[i].itemCode)
                        @Html.HiddenFor(m => Model.ItemsSelected[i].itemType)
                        @Html.HiddenFor(m => Model.ItemsSelected[i].itemDescription)
                        @Html.HiddenFor(m => Model.ItemsSelected[i].UnidadDeMedida)
                        @Html.HiddenFor(m => Model.ItemsSelected[i].Quantity)
                        @Html.HiddenFor(m => Model.ItemsSelected[i].Quitar, new {@class ="Quitar"})
                        @Html.HiddenFor(m => Model.ItemsSelected[i].itemType)
                        <th class="text-center"><button type="button" class="btn btn-xs btn-danger btr" id="@i"><span class="fa fa-remove"></span></button></th>
                    </tr>
                }
            </tbody>
        </table>
    }
}
@section scripts{
    <script type="text/javascript">
        $('.btr').click(function () {
            var id = $(this).attr('id');
            var r = $('.' + id);
            $(this).parent().parent().children('.Quitar').val('True')
            r.hide();
        })
    </script>
    }

7 - CMS/MVC/Views/transfers/ResumeReverse.cshtml
@model List<admin_usuarios.Models.ItemComponent>
@{
    ViewBag.Title = "TransferResume";
}

<style>
    .float {
        position: fixed;
        bottom: 25px;
        right: 25px;
    }
</style>

<div class="page-header">
    @if (ViewBag.option == "1")
    {
        <h2>Resumen de la Transferencia</h2>
        <p class="label label-danger">**Los item marcados en ROJO no tienen Cantidad disponible para completar la Transferencia.</p> <br />
        <p class="label label-danger">**Si existe un item en color ROJO el boton de traslados estará deshabilitado.</p>
    }
    else
    {
        <h2>Resultado del Traslado</h2>
        if (ViewBag.mensaje != null)
        {
            <label class="label label-danger">@ViewBag.mensaje</label>
        }
        else
        {
            <label class="label label-success">**Resusltados de la Transferencia por item.</label> <br />
        }

    }
</div>

<hr />

@using (Html.BeginForm("ReverseConfirm", "transfers", FormMethod.Post))
{
    <div class="row">
        <div class="col-xs-12">
            <table class="table table-hover table-responsive">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Descripción</th>
                        <th class="text-right">Cantidad Requerida</th>
                        <th class="text-right">Cantidad disponible</th>
                        <th class="text-right">Unidad de Medida</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        int i = Model.IndexOf(item);
                        string clase = item.ComponentOriginalQty > item.ComponentStock ? "danger" : "";
                        @Html.HiddenFor(m => Model[i].ComponentDescription)
                        @Html.HiddenFor(m => Model[i].ComponentId)
                        @Html.HiddenFor(m => Model[i].ComponentOriginalQty)
                        @Html.HiddenFor(m => Model[i].ComponentStock)
                        @Html.HiddenFor(m => Model[i].MasterID)
                        @Html.HiddenFor(m => Model[i].UOM)

                        <tr class="@clase">
                            <td>@item.ComponentId</td>
                            <td>@item.ComponentDescription</td>
                            <td class="text-right">@item.ComponentOriginalQty.ToString("N4")</td>
                            <td class="text-right">@item.ComponentStock.ToString("N4")</td>
                            <td class="text-right">@item.UOM</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header text-center">
                    <h2 class="modal-title" id="exampleModalLongTitle">Ejecutando la Transferencia</h2>
                </div>
                <div class="modal-body text-center">
                    <h2>
                        <label class="label label-danger">Por favor no recargue la página.</label>
                    </h2>
                    <i class="fa fa-refresh fa-spin fa-5x fa-fw"></i>
                    <h2>
                        <label class="label label-danger">Por favor no recargue la página.</label>
                    </h2>
                </div>
            </div>
        </div>
    </div>

    if (ViewBag.option == "1")
    {
        <div class="float">
            @{
                string clase2 = "";
                int c = Model.Where(a => a.ComponentOriginalQty > a.ComponentStock).Count();
                if (c > 0)
                {
                    clase2 = "disabled";
                }
            }
            <button type="submit" id="btnsub" class="btn btn-success @clase2" @clase2><i class="fa fa-check"></i> Ejecutar Transferencia</button>
        </div>
    }
}
@section scripts{
    <script type="text/javascript">
        $("#btnsub").click(function (e) {
            //e.preventDefault();
            $("#exampleModalCenter").modal({
                'backdrop': 'static',
                'keyboard': false
            });
        })
    </script>
}

7 - CMS/MVC/Views/transfers/SelectTheater.cshtml
@using (Html.BeginForm("VerifyCandiesByTheater", "transfers", FormMethod.Post))
{
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <select id="CinemaId" name="CinemaId" class="form-control">
                <option selected value="0000"><text>Seleccione Un Cine</text></option>
                @*<optgroup label="Pruebas">
                        <option value="PIR1028"><text>La Piramide</text></option>
                    </optgroup>*@
                <optgroup label="Caracas">
                    <option value="LDR1027"><text>Lider</text></option>
                    <option value="LNA1001"><text>Los Naranjos</text></option>
                    <option value="MLN1026"><text>Millenium</text></option>
                    <option value="SAM1005"><text>Sambil Caracas</text></option>
                </optgroup>
                <optgroup label="Barquisimeto">
                    <option value="SBQ1025"><text>Sambil Barquisimeto</text></option>
                </optgroup>
                <optgroup label="Maracaibo">
                    <option value="SMB1017"><text>Sambil Maracaibo</text></option>
                </optgroup>
                <optgroup label="Maracay">
                    <option value="HIP1015"><text>Hiperjumbo</text></option>
                </optgroup>
                <optgroup label="San Cristobal">
                    <option value="SSC1024"><text>Sambil San Cristobal</text></option>
                </optgroup>
                <optgroup label="Valencia">
                    <option value="SVA1014"><text>Sambil Valencia</text></option>
                </optgroup>
            </select>
        </div>
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
            <button id="Buscar" class="btn btn-danger" type="submit">
                <span class="glyphicon glyphicon-search"> Buscar </span>
            </button>
        </div>
    </div>
}
@section scripts{
    <script type="text/javascript">
        $('#Buscar').click(function (e) {
            //alert($('#TransactionId').val());
            //alert($('#CinemaId').val());
            if ($('#TransactionId').val() == '' || $('#CinemaId').val() == '0000') {
                alert('Por Favor Introduzca los Datos Correctamente Codigo y Seleccione el Cine');
                e.preventDefault();
            }
        })
    </script>
}

7 - CMS/MVC/Views/transfers/TransferConfirmation.cshtml
@model List<admin_usuarios.Models.ItemAndComponets>
@{
    ViewBag.Title = "TransferConfirmation";
}

<style>
    .float {
        position: fixed;
        bottom: 25px;
        right: 25px;
    }
</style>
<div class="page-header">
    <h2>Confirmacion de items para Transferencia de inventario</h2>
    <p class="label label-info">Nota: si existe algun item en color rojo, no podrá procesar la Transferencia.</p>
    <br />
    <p class="label label-info">por favor regrese a la vista anterior y elimine el item que esta en color rojo</p>
</div>

@using (Html.BeginForm("TransferResume", "transfers", FormMethod.Post))
{
    <div class="row">
        @foreach (var item in Model)
        {
            int i = Model.IndexOf(item);
            @Html.HiddenFor(m => Model[i].PrincipalItem.itemCode)
            @Html.HiddenFor(m => Model[i].PrincipalItem.itemDescription)
            @Html.HiddenFor(m => Model[i].PrincipalItem.itemType)
            @Html.HiddenFor(m => Model[i].PrincipalItem.UnidadDeMedida)
            @Html.HiddenFor(m => Model[i].PrincipalItem.Quitar)
            @Html.HiddenFor(m => Model[i].PrincipalItem.Quantity)
            string clase = item.TransferAble == true ? "panel-success" : "panel-danger";
            <div class="col-xs-12">
                <div class="panel @clase">
                    <div class="panel-heading"><b>@item.PrincipalItem.Quantity @item.PrincipalItem.itemDescription</b></div>
                    <div class="panel-body">
                        <table class="table table-responsive table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>Descripcion</th>
                                    <th class="text-right">Cantidad Original</th>
                                    <th class="text-right">Cantidad Requerida</th>
                                    <th class="text-right">Stock Disponible</th>
                                    <th class="text-right">Unidad de Medida</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item2 in item.ItemComponents)
                                {
                                    int i2 = item.ItemComponents.IndexOf(item2);
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentDescription)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentId)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentOriginalQty)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentStock)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].UOM)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].MasterID)
                                    decimal r = item2.ComponentOriginalQty;
                                    if (item.PrincipalItem.itemType != null)
                                    {
                                        r = (decimal)item.PrincipalItem.Quantity * item2.ComponentOriginalQty;
                                    }
                                    <tr>
                                        <th>@item2.ComponentDescription</th>
                                        <th class="text-right">@item2.ComponentOriginalQty.ToString("N4")</th>
                                        <th class="text-right">@r.ToString("N4")</th>
                                        <th class="text-right">@item2.ComponentStock.ToString("N4")</th>
                                        <th class="text-right">@item2.UOM</th>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="float">
        @{
            string clase2 = "";
            int c = Model.Where(a => a.TransferAble == false).Count();
            if (c > 0)
            {
                clase2 = "disabled";
            }
        }
        <button type="submit" class="btn btn-primary @clase2" @clase2><i class="fa fa-check"></i> Procesar Transferencia</button>
    </div>
            }

7 - CMS/MVC/Views/transfers/TransferConfirmation2.cshtml
@model List<admin_usuarios.Models.ItemAndComponets>
@{
    ViewBag.Title = "TransferConfirmation";
}

<style>
    .float {
        position: fixed;
        bottom: 25px;
        right: 25px;
    }
</style>
<div class="page-header">
    <h2>Confirmacion de items para traslado de inventario</h2>
    <p class="label label-info">Nota: si existe algun item en color rojo, no podrá procesar la Transferencia.</p>
    <br />
    <p class="label label-info">por favor regrese a la vista anterior y elimine el item que esta en color rojo</p>
</div>

@using (Html.BeginForm("ResumeReverse", "transfers", FormMethod.Post))
{
    <div class="row">
        @foreach (var item in Model)
        {
            int i = Model.IndexOf(item);
            @Html.HiddenFor(m => Model[i].PrincipalItem.itemCode)
            @Html.HiddenFor(m => Model[i].PrincipalItem.itemDescription)
            @Html.HiddenFor(m => Model[i].PrincipalItem.itemType)
            @Html.HiddenFor(m => Model[i].PrincipalItem.UnidadDeMedida)
            @Html.HiddenFor(m => Model[i].PrincipalItem.Quitar)
            @Html.HiddenFor(m => Model[i].PrincipalItem.Quantity)
            string clase = item.TransferAble == true ? "panel-success" : "panel-danger";
            <div class="col-xs-12">
                <div class="panel @clase">
                    <div class="panel-heading"><b>@item.PrincipalItem.Quantity @item.PrincipalItem.itemDescription</b></div>
                    <div class="panel-body">
                        <table class="table table-responsive table-hover table-condensed">
                            <thead>
                                <tr>
                                    <th>Descripcion</th>
                                    <th class="text-right">Cantidad Original</th>
                                    <th class="text-right">Cantidad Requerida</th>
                                    <th class="text-right">Stock Disponible</th>
                                    <th class="text-right">Unidad de Medida</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item2 in item.ItemComponents)
                                {
                                    int i2 = item.ItemComponents.IndexOf(item2);
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentDescription)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentId)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentOriginalQty)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].ComponentStock)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].UOM)
                                    @Html.HiddenFor(m => Model[i].ItemComponents[i2].MasterID)
                                    decimal r = item2.ComponentOriginalQty;
                                    if (item.PrincipalItem.itemType != null)
                                    {
                                        r = (decimal)item.PrincipalItem.Quantity * item2.ComponentOriginalQty;
                                    }
                                    <tr>
                                        <th>@item2.ComponentDescription</th>
                                        <th class="text-right">@item2.ComponentOriginalQty.ToString("N4")</th>
                                        <th class="text-right">@r.ToString("N4")</th>
                                        <th class="text-right">@item2.ComponentStock.ToString("N4")</th>
                                        <th class="text-right">@item2.UOM</th>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="float">
        @{
            string clase2 = "";
            int c = Model.Where(a => a.TransferAble == false).Count();
            if (c > 0)
            {
                clase2 = "disabled";
            }
        }
        <button type="submit" class="btn btn-primary @clase2" @clase2><i class="fa fa-check"></i> Procesar Transferencia</button>
    </div>
            }